#############################################################################
# Makefile for building: Schoolware.app/Contents/MacOS/Schoolware
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu Jan 31 12:21:10 2013
# Project:  Schoolware.pro
# Template: app
# Command: /Developer/Tools/Qt/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Schoolware.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTOUCH_OPTIMIZED_NAVIGATION -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtWebKit.framework/Versions/4/Headers -I/usr/include/QtWebKit -I/usr/include -Ihtml5applicationviewer -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtWebKit -framework QtGui -framework QtCore -framework QtNetwork 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/Tools/Qt/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		jsbridgeobj.cpp \
		downloadmanager.cpp \
		html5applicationviewer/html5applicationviewer.cpp moc_html5applicationviewer.cpp \
		moc_jsbridgeobj.cpp \
		moc_downloadmanager.cpp
OBJECTS       = main.o \
		jsbridgeobj.o \
		downloadmanager.o \
		html5applicationviewer.o \
		moc_html5applicationviewer.o \
		moc_jsbridgeobj.o \
		moc_downloadmanager.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		html5applicationviewer/html5applicationviewer.pri \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		Schoolware.pro
QMAKE_TARGET  = Schoolware
DESTDIR       = 
TARGET        = Schoolware.app/Contents/MacOS/Schoolware

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Schoolware.app/Contents/PkgInfo Schoolware.app/Contents/Resources/empty.lproj Schoolware.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Schoolware.app/Contents/MacOS/ || $(MKDIR) Schoolware.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Schoolware.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		html5applicationviewer/html5applicationviewer.pri \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtWebKit.framework/QtWebKit.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Schoolware.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
html5applicationviewer/html5applicationviewer.pri:
/usr/local/Qt4.8/mkspecs/features/release.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtWebKit.framework/QtWebKit.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Schoolware.pro

Schoolware.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Schoolware.app/Contents || $(MKDIR) Schoolware.app/Contents 
	@$(DEL_FILE) Schoolware.app/Contents/PkgInfo
	@echo "APPL????" >Schoolware.app/Contents/PkgInfo
Schoolware.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Schoolware.app/Contents/Resources || $(MKDIR) Schoolware.app/Contents/Resources 
	@touch Schoolware.app/Contents/Resources/empty.lproj
	
Schoolware.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Schoolware.app/Contents || $(MKDIR) Schoolware.app/Contents 
	@$(DEL_FILE) Schoolware.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Schoolware,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.8/mkspecs/macx-g++/Info.plist.app >Schoolware.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Schoolware1.0.0 || $(MKDIR) .tmp/Schoolware1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Schoolware1.0.0/ && $(COPY_FILE) --parents html5applicationviewer/html5applicationviewer.h jsbridgeobj.h downloadmanager.h .tmp/Schoolware1.0.0/ && $(COPY_FILE) --parents main.cpp jsbridgeobj.cpp downloadmanager.cpp html5applicationviewer/html5applicationviewer.cpp .tmp/Schoolware1.0.0/ && (cd `dirname .tmp/Schoolware1.0.0` && $(TAR) Schoolware1.0.0.tar Schoolware1.0.0 && $(COMPRESS) Schoolware1.0.0.tar) && $(MOVE) `dirname .tmp/Schoolware1.0.0`/Schoolware1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Schoolware1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Schoolware.app
	-$(DEL_FILE) Makefile


first: $(first) copydeploymentfolders

copydeploymentfolders:
	@echo Copying application data... && $(MKDIR) "/Users/costas/Documents/Qt Workspace/Schoolware/Schoolware.app/Contents/Resources/." && $(COPY_DIR) "/Users/costas/Documents/Qt Workspace/Schoolware/../Schoolware/SchoolWareWebSite" "/Users/costas/Documents/Qt Workspace/Schoolware/Schoolware.app/Contents/Resources/."

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_html5applicationviewer.cpp moc_jsbridgeobj.cpp moc_downloadmanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_html5applicationviewer.cpp moc_jsbridgeobj.cpp moc_downloadmanager.cpp
moc_html5applicationviewer.cpp: html5applicationviewer/html5applicationviewer.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ html5applicationviewer/html5applicationviewer.h -o moc_html5applicationviewer.cpp

moc_jsbridgeobj.cpp: downloadmanager.h \
		jsbridgeobj.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ jsbridgeobj.h -o moc_jsbridgeobj.cpp

moc_downloadmanager.cpp: downloadmanager.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ downloadmanager.h -o moc_downloadmanager.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all: html5applicationviewer.moc
compiler_moc_source_clean:
	-$(DEL_FILE) html5applicationviewer.moc
html5applicationviewer.moc: html5applicationviewer/html5applicationviewer.h \
		html5applicationviewer/html5applicationviewer.cpp
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ html5applicationviewer/html5applicationviewer.cpp -o html5applicationviewer.moc

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

main.o: main.cpp jsbridgeobj.h \
		downloadmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

jsbridgeobj.o: jsbridgeobj.cpp jsbridgeobj.h \
		downloadmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsbridgeobj.o jsbridgeobj.cpp

downloadmanager.o: downloadmanager.cpp downloadmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadmanager.o downloadmanager.cpp

html5applicationviewer.o: html5applicationviewer/html5applicationviewer.cpp html5applicationviewer/html5applicationviewer.h \
		html5applicationviewer.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o html5applicationviewer.o html5applicationviewer/html5applicationviewer.cpp

moc_html5applicationviewer.o: moc_html5applicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_html5applicationviewer.o moc_html5applicationviewer.cpp

moc_jsbridgeobj.o: moc_jsbridgeobj.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jsbridgeobj.o moc_jsbridgeobj.cpp

moc_downloadmanager.o: moc_downloadmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadmanager.o moc_downloadmanager.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Schoolware/./ || $(MKDIR) $(INSTALL_ROOT)/opt/Schoolware/./ 
	-$(INSTALL_DIR) /Users/costas/Documents/Qt\ Workspace/Schoolware/SchoolWareWebSite $(INSTALL_ROOT)/opt/Schoolware/./


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Schoolware/./SchoolWareWebSite
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Schoolware/./ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Schoolware/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/Schoolware/bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/Schoolware/bin/Schoolware.app"
	
	-$(INSTALL_DIR) "Schoolware.app" "$(INSTALL_ROOT)/opt/Schoolware/bin/Schoolware.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/Schoolware/bin/Schoolware.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Schoolware/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

